export const themes = {
    'Cappuccino': {
        '--faded': '#854442a2',
        '--general-font': '#854442',
        '--header': '#2c2121',
        '--header-font': '#fff4e6',
        '--background': '#fff4e6',
        '--text-display': '#3c2f2f',
        '--text-display-font': '#e4d2c2',
        '--input-border': '1px solid #be9b7b',
        '--explanation': 400,
    },
    'Midnight': {
        '--faded': '#444444',
        '--general-font': '#DDDDDD',
        '--header': '#101013',
        '--header-font': '#DDDDDD',
        '--background': '#17171D',
        '--text-display': '#FAEBD72F',
        '--text-display-font': '#DDDDDD',
        '--input-border': 'none',
        '--explanation': 300,
    },
    'Mocha Rose': {
        '--faded': '#8B8B8B',
        '--general-font': '#1A1A1A',
        '--header': '#a8817d',
        '--header-font': '#1A1A1A',
        '--background': '#F8FAF1',
        '--text-display': '#DDC8C4',
        '--text-display-font': '#1A1A1A',
        '--input-border': '1px solid #896A67',
        '--explanation': 400,
    },
    'Peach Candy': {
        '--faded': '#a89c83',
        '--general-font': '#1A1A1A',
        '--header': '#ED254E',
        '--header-font': '#FFFDF3',
        '--background': '#fff8e1',
        '--text-display': '#F9DC5C',
        '--text-display-font': '#1A1A1A',
        '--input-border': '1px solid #C7B872',
        '--explanation': 400,
    },
    'Pitch Black': {
        '--faded': '#838383',
        '--general-font': '#ffffff',
        '--header': '#000000',
        '--header-font': '#FFFDF3',
        '--background': '#000000',
        '--text-display': '#000000',
        '--text-display-font': '#FFFFFF',
        '--input-border': 'none',
        '--explanation': 300,
    },
    'Sandy Shores': {
        '--faded': '#00152498',
        '--general-font': '#042035',
        '--header': '#073b61',
        '--header-font': '#ffffff',
        '--background': '#48b2c2',
        '--text-display': '#dfa168',
        '--text-display-font': '#000e18',
        '--input-border': '1px solid #FF7D00',
        '--explanation': 400,
    },
    'Tropical Smoothie': {
        '--faded': '#78a84b',
        '--general-font': '#D63447',
        '--header': '#D63447',
        '--header-font': '#FFFDF3',
        '--background': '#ffe26d',
        '--text-display': '#78a84b',
        '--text-display-font': '#FFFFFF',
        '--input-border': '1px solid #D63447',
        '--explanation': 400,
    },
    'Tuxedo': {
        '--faded': '#838383',
        '--general-font': '#000000',
        '--header': '#000000',
        '--header-font': '#ffffff',
        '--background': '#ffffff',
        '--text-display': '#ffffff',
        '--text-display-font': '#000000',
        '--input-border': '1px solid #000000',
        '--explanation': 400,
    },
    'Water Bearer': {
        '--faded': '#76b4bd',
        '--general-font': '#58668b',
        '--header': '#58668b',
        '--header-font': '#FFFDF3',
        '--background': '#ebf4f6',
        '--text-display': '#76b4bd',
        '--text-display-font': '#ffffff',
        '--input-border': '1px solid #58668b',
        '--explanation': 400,
    },
};