export const ONE_SECOND = 1000;
export const ONE_MINUTE = 60 * ONE_SECOND;
export const ONE_HOUR = 60 * ONE_MINUTE;

const TEST_DURATION = 2 * ONE_HOUR;

// TODO: REPLACE  TEST_DURATION FOR 60s AFTER FINISHING TEST BEHAVIOUR
export const DEFAULT_TEST_DURATION = TEST_DURATION;
export const CHARS_IN_WORD = 5;
export const WORDS_PER_WORDBLOCK = 8;
export const QUOTES_LOADED_PER_TEST_MINUTE = 25;
