const themeProperties = [
    '--header',
    '--background',
    '--words-box',
    '--text-main',
    '--text-faded',
    '--text-header',
    '--text-words-box',
    '--input-border',
] as const;
type ThemeProperties = (typeof themeProperties)[number];
export type Theme = Record<ThemeProperties, string>;

type Themes = { [key: string]: Theme };
export const THEMES = {
    Cappuccino: {
        '--header': '#2c2121',
        '--background': '#fff4e6',
        '--words-box': '#3c2f2f',
        '--text-main': '#854442',
        '--text-faded': '#854442a2',
        '--text-header': '#fff4e6',
        '--text-words-box': '#e4d2c2',
        '--input-border': '1px solid #be9b7b',
    },
    Midnight: {
        '--header': '#101013',
        '--background': '#17171D',
        '--words-box': '#FAEBD72F',
        '--text-main': '#DDDDDD',
        '--text-faded': '#444444',
        '--text-header': '#DDDDDD',
        '--text-words-box': '#DDDDDD',
        '--input-border': 'none',
    },
    'Mocha Rose': {
        '--header': '#a8817d',
        '--background': '#F8FAF1',
        '--words-box': '#DDC8C4',
        '--text-main': '#1A1A1A',
        '--text-faded': '#8B8B8B',
        '--text-header': '#1A1A1A',
        '--text-words-box': '#1A1A1A',
        '--input-border': '1px solid #896A67',
    },
    'Peach Candy': {
        '--header': '#ED254E',
        '--background': '#fff8e1',
        '--words-box': '#F9DC5C',
        '--text-main': '#1A1A1A',
        '--text-faded': '#a89c83',
        '--text-header': '#FFFDF3',
        '--text-words-box': '#1A1A1A',
        '--input-border': '1px solid #C7B872',
    },
    'Pitch Black': {
        '--header': '#000000',
        '--background': '#000000',
        '--words-box': '#000000',
        '--text-main': '#ffffff',
        '--text-faded': '#838383',
        '--text-header': '#FFFDF3',
        '--text-words-box': '#FFFFFF',
        '--input-border': 'none',
    },
    'Sandy Shores': {
        '--header': '#073b61',
        '--background': '#48b2c2',
        '--words-box': '#dfa168',
        '--text-main': '#042035',
        '--text-faded': '#00152498',
        '--text-header': '#ffffff',
        '--text-words-box': '#000e18',
        '--input-border': '1px solid #FF7D00',
    },
    'Tropical Smoothie': {
        '--header': '#D63447',
        '--background': '#ffe26d',
        '--words-box': '#78a84b',
        '--text-main': '#D63447',
        '--text-faded': '#78a84b',
        '--text-header': '#FFFDF3',
        '--text-words-box': '#FFFFFF',
        '--input-border': '1px solid #D63447',
    },
    Tuxedo: {
        '--header': '#000000',
        '--background': '#ffffff',
        '--words-box': '#ffffff',
        '--text-main': '#000000',
        '--text-faded': '#838383',
        '--text-header': '#ffffff',
        '--text-words-box': '#000000',
        '--input-border': '1px solid #000000',
    },
    'Water Bearer': {
        '--header': '#58668b',
        '--background': '#ebf4f6',
        '--words-box': '#76b4bd',
        '--text-main': '#58668b',
        '--text-faded': '#76b4bd',
        '--text-header': '#FFFDF3',
        '--text-words-box': '#ffffff',
        '--input-border': '1px solid #58668b',
    },
} satisfies Themes;
export type ThemeName = keyof typeof THEMES;
export type SetThemeAction = (theme: ThemeName) => void;
